ZSH=$HOME/.oh-my-zsh
ZSH_THEME="bryankendall"

DISABLE_UPDATE_PROMPT=true
MYVIMRC=$HOME/dotfiles.git/vim/vimrc

if [ -e '/usr/local/bin/virtualenvwrapper.sh' ]
then
  export WORKON_HOME=$HOME/.virtualenvs
  source /usr/local/bin/virtualenvwrapper.sh
fi

if [ -e '/usr/local/go' ]
then
  export PATH=$PATH:/usr/local/go/bin
fi

if [ -d "$HOME/.ssh/config.d" ]; then
  rm -f $HOME/.ssh/config
  cat $HOME/.ssh/config.d/*.config >> $HOME/.ssh/config
fi

NVM_LAZY_LOAD=true
plugins=(git brew docker zsh-nvm npm)

export EDITOR='vim'
