ZSH=$HOME/.oh-my-zsh
ZSH_THEME="kennethreitz"

DISABLE_UPDATE_PROMPT=true
MYVIMRC=$HOME/dotfiles.git/vim/vimrc

export UPDATE_ZSH_DAYS=13

plugins=(git)

export EDITOR='vim'

source $ZSH/oh-my-zsh.sh
