syntax enable
let g:solarized_termcolors=256
set t_Co=256
colorscheme solarized
set background=dark

filetype on

set nocompatible
set number

" tabs stuff
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" make things better
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set visualbell
set ttyfast
set ruler
set backspace=indent,eol,start
set undofile
set undodir=~/.vim/undodir
set backupdir=~/.vim/backup,/tmp
set directory=~/.vim/backup,/tmp

" highlighting
nnoremap <cr> :nohl<cr><cr> 

" searching/moving
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch

" long lines
set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=80,100

" modelines
set modeline
set modelines=3

" status line
set statusline=%<%f\ (%{&ft})\ %-4(%m%)%=%-19(%3l,%02c%03V%)

" syntastic
execute pathogen#infect()
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_loc_list=1
let g:syntastic_check_on_open=0
let g:syntastic_check_on_wq=0
let g:syntastic_javascript_checkers=[]
if filereadable('.jshintrc')
  call add(g:syntastic_javascript_checkers, 'jshint')
end
if filereadable('.eslintrc')
  call add(g:syntastic_javascript_checkers, 'eslint')
  if filereadable('./node_modules/.bin/eslint')
    let g:syntastic_javascript_eslint_exec='./node_modules/.bin/eslint'
  end
end
if filereadable('.flowconfig')
  call add(g:syntastic_javascript_checkers, 'flow')
end
let g:syntastic_aggregate_errors=1
let g:syntastic_enable_signs=0

" command-t
call pathogen#helptags()
let g:CommandTFileScanner='ruby'
let g:CommandTWildIgnore=&wildignore . ",**/node_modules/*"
